# Generated by Django 3.2.7 on 2021-10-25 15:11

import datetime
from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_views', models.IntegerField(auto_created=True, default=0, editable=False, verbose_name='Счетчик просмотров')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to=records.models.Records.upload_path, verbose_name='Файл')),
                ('type', models.CharField(choices=[('video', 'Видео'), ('doc', 'Документ')], default='video', max_length=20, verbose_name='Тип контента')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='Дата мероприятия')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления записи')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение данных записи')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-date', 'title'],
            },
        ),
    ]
