# Generated by Django 3.2.7 on 2021-11-16 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата мероприятия'),
        ),
    ]
